site_name: rustfst-python
site_url: https://github.com/Garvys/rustfst
nav:
    - Home: index.md
    - About: about.md
    - API : api.md
    - Code Reference: reference/
#    - Code Reference:
#      - algorithms:
#        - reverse: reference/rustfst/algorithms/reverse.md

theme: material
repo_url: https://github.com/Garvys/rustfst
repo_name: rustfst
plugins:
  - search
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      watch:
        - ../rustfst
        - docs/gen_ref_pages.py
      default_handler: python
      handlers:
        python:
          rendering:
            enable_inventory: true
            heading_level: 3
            separate_signature: true
            show_signature_annotations: true
            show_if_no_docstring: true
            show_category_heading: true
            show_object_full_path: true

