# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.7"
    rust: "1.55"


# Build documentation in the docs/ directory with Sphinx
#sphinx:
#  configuration: rustfst-python/docs/source/conf.py
mkdocs:
  configuration: mkdocs.yml

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
  install:
  - requirements: rustfst-python/requirements-setup.txt
  - method: pip
    path: rustfst-python
  - requirements: requirements-mkdocs.txt
