language: rust
cache:
  - cargo
  - directories:
    - cached
python: '3.6'
rust:
- stable
env:
- RUST_BACKTRACE=1
script: ./.travis.sh
before_install:
  - sudo apt-get update
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install python3.6
