[package]
name = "rustfst"
version = "0.1.0"
authors = ["Alexandre Caulier<alexandre.caulier@protonmail.com>"]

[dependencies]
failure = "0.1"

[dev-dependencies]
counter = "0.4"
itertools = "0.7"
rand = "0.5.5"
