[package]
name = "rustfst-ffi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
ffi-convert = "0.5"
libc = "0.2.42"
rustfst = {path = "../rustfst"}
