[package]
name = "rustfst-cli"
version = "0.1.0"
authors = ["Garvys <alexandre.caulier@orange.fr>"]
edition = "2018"

[dependencies]
clap = "2.33"
colored = "1.8"
log = "0.4"
env_logger = "0.6"
failure = '0.1'
rustfst = {path = "../rustfst"}
