[package]
name = "rustfst-cli"
version = "0.3.0"
authors = ["Garvys <alexandre.caulier@orange.fr>"]
edition = "2018"

[dependencies]
anyhow = '1.0'
clap = "2.33"
colored = "1.8"
env_logger = "0.6"
exitcode = "1.1"
log = "0.4"
rustfst = {path = "../rustfst"}
unsafe_unwrap = "0.1"
