name: Native Linux

on:
  pull_request:
  push:
  schedule:
    - cron:  '0 9 * * *'

jobs:
  linux:
    strategy:
      matrix:
        rust: [ 1.49.0, stable ]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Cache Openfst build
      uses: actions/cache@v2
      env:
        cache-name: cache-openfst-build
      with:
        path: openfst-1.7.2
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Native script
      env:
        RUST_VERSION: ${{matrix.rust}}
      run: .ci/native.sh
